baseurl: "/pamylka"            # Leave empty for GitHub Pages
title: "PAMYÅKA zine"
collections:
  articles:
    output: true # Ensures HTML files are generated
    permalink: /:path/ # Custom URL structure
  news:
    output: true # Ensures HTML files are generated
    permalink: /:path/ # Custom URL structure
